name: go-ci

on: [push]

jobs:
  setup:
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version:^1.16
      - uses: actions/checkout@v2
  test:
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: go test ./...